name: WoW Addon Release

on:
  workflow_call:

jobs:
  prepare:
    name: Latest commit
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.latest_commit.outputs.commit }}
      reponame: ${{ steps.repo_name.outputs.reponame }}
      tagname: ${{ steps.get_tag.outputs.tagname }}
    steps:
    - name: Clone 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set latest_commit
      id: latest_commit
      run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Get latest tag
      id: get_tag
      run: echo "tagname=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

    - name: Get repo name
      id: repo_name
      run: echo "reponame=$(basename ${{ github.repository }})" >> $GITHUB_OUTPUT
  
  release:
    name: Create GitHub Release
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
      if: github.event_name != 'push'

    - name: Set tag name
      id: tag
      run: |
        if [[ "${{ github.event_name }}" != "push" ]]; then
          tag=v$(date +%Y%m%d.%H%M%S)
        else
          tag="${{ needs.prepare.outputs.tagname }}"
        fi
    
    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        tag="${{ needs.prepare.outputs.tagname }}"
        body="${{ needs.prepare.outputs.reponame }}@${{ needs.prepare.outputs.commit }}"
        gh release create --draft "$tag" --title "$tag" --notes "$body"
  
  build:
    name: Zip and attach
    needs: [prepare, release]
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    
    - name: Zip Folder
      run: |
        cd ../
        rm -rf ${{ needs.prepare.outputs.reponame }}*-classic.zip
        zip -r ${{ needs.prepare.outputs.reponame }}-${{ needs.prepare.outputs.tagname }}-classic.zip ${{ needs.prepare.outputs.reponame }} -x "${{ needs.prepare.outputs.reponame }}/.git/*" "${{ needs.prepare.outputs.reponame }}/.github/*"

    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        cd ../
        gh release upload "${{ needs.prepare.outputs.tagname }}" "${{ needs.prepare.outputs.reponame }}-${{ needs.prepare.outputs.tagname }}-classic.zip"

  publish:
    name: Publish Release
    needs: [prepare, release, build]
    runs-on: ubuntu-latest
    environment: Release
    steps:
    - name: Publish Release
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: gh release edit "${{ needs.prepare.outputs.tagname }}" --draft=false
